version: '2'

services:
  server:
    image: node:8.9-alpine
    ports:
    - "3000:3000"
    volumes:
    - ../:/app
    working_dir: /app

  database:
    image: mariadb
    volumes:
    - "./database:/var/lib/mysql"
    ports:
    - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: jeremy


#  client:
#    image: node:8.9-alpine
#    ports:
#    - "8081:8080"
#    volumes:
#    - ../:/APP
#    working_dir: /app
#    command: npm run client:serve
